/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaires;

import Entite.Intervenant;
import Entite.Proposition;
import Entite.Theme;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MECHACK
 */
public class Fproposition extends javax.swing.JFrame {

    /**
     * Creates new form Fproposition
     */
    Proposition pr = new Proposition();
    Intervenant itvn = new Intervenant();
    Theme thm = new Theme();

    public Fproposition() {
        initComponents();
        itvn.Charger(ComboInterv);
        thm.Charger(ComboTheme);
        pr.Remplir(jTable1, "select Propositions.Id_Proposition, Intervenants.Noms,Themes.LibeleTheme,Propositions.Resume,\n"
                + "Propositions.Date from Intervenants,Themes,Propositions\n"
                + "where Propositions.Id_Intervenant=Intervenants.Id_Intervenant and \n"
                + "Propositions.Id_Theme=Themes.Id_Theme");

    }

    void Nettoyer() {
        textCodePropo.setText("");
        ComboInterv.setSelectedItem("");
        ComboTheme.setSelectedItem("");
        ResumeArea.setText("");
        textDate.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fsave = new javax.swing.JFrame();
        BgP1 = new javax.swing.JPanel();
        textDate = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        textCodePropo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        LblExit1 = new javax.swing.JLabel();
        LblInterv = new javax.swing.JLabel();
        LblDate = new javax.swing.JLabel();
        LblCodeP = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        LblTheme = new javax.swing.JLabel();
        LblResume = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResumeArea = new javax.swing.JTextArea();
        BtnDelete = new javax.swing.JButton();
        BtnSave1 = new javax.swing.JButton();
        BtnUpdate1 = new javax.swing.JButton();
        BtnDelete1 = new javax.swing.JButton();
        ComboTheme = new javax.swing.JComboBox();
        ComboInterv = new javax.swing.JComboBox();
        BgP = new javax.swing.JPanel();
        Pvertical = new javax.swing.JPanel();
        BtnIntervenant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnIdentification = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnTheme = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        LblExit = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnMiseAJour = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        textRecherche = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        fsave.setAlwaysOnTop(true);

        BgP1.setBackground(new java.awt.Color(32, 33, 35));
        BgP1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BgP1MouseDragged(evt);
            }
        });
        BgP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BgP1MousePressed(evt);
            }
        });
        BgP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textDate.setBackground(new java.awt.Color(32, 33, 36));
        textDate.setForeground(new java.awt.Color(204, 255, 255));
        textDate.setBorder(null);
        textDate.setCaretColor(new java.awt.Color(255, 255, 255));
        textDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDateFocusGained(evt);
            }
        });
        BgP1.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 290, 20));
        BgP1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 290, 10));

        textCodePropo.setBackground(new java.awt.Color(32, 33, 36));
        textCodePropo.setForeground(new java.awt.Color(204, 255, 255));
        textCodePropo.setBorder(null);
        textCodePropo.setCaretColor(new java.awt.Color(255, 255, 255));
        textCodePropo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCodePropoFocusGained(evt);
            }
        });
        textCodePropo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textCodePropoMouseClicked(evt);
            }
        });
        BgP1.add(textCodePropo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 280, 20));
        BgP1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, 10));
        BgP1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 290, 10));

        LblExit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblExit1.setForeground(new java.awt.Color(57, 113, 177));
        LblExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_Window_30px.png"))); // NOI18N
        LblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblExit1MouseClicked(evt);
            }
        });
        BgP1.add(LblExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 20, 20));

        LblInterv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblInterv.setForeground(new java.awt.Color(51, 52, 54));
        LblInterv.setText("Intervenant");
        BgP1.add(LblInterv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        LblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblDate.setForeground(new java.awt.Color(51, 52, 54));
        LblDate.setText("Date");
        BgP1.add(LblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        LblCodeP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblCodeP.setForeground(new java.awt.Color(57, 113, 177));
        LblCodeP.setText("Code Proposition");
        BgP1.add(LblCodeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        BgP1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, 10));

        LblTheme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblTheme.setForeground(new java.awt.Color(51, 52, 54));
        LblTheme.setText("Theme");
        BgP1.add(LblTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        LblResume.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblResume.setForeground(new java.awt.Color(51, 52, 54));
        LblResume.setText("Resumé");
        BgP1.add(LblResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        BgP1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 370, 10));

        ResumeArea.setColumns(20);
        ResumeArea.setLineWrap(true);
        ResumeArea.setRows(5);
        ResumeArea.setBorder(null);
        ResumeArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ResumeAreaFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(ResumeArea);

        BgP1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 370, 150));

        BtnDelete.setBackground(new java.awt.Color(0, 0, 0));
        BtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(126, 87, 194));
        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Broom_25px.png"))); // NOI18N
        BtnDelete.setText("Clean");
        BtnDelete.setBorder(null);
        BtnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        BgP1.add(BtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 90, 30));

        BtnSave1.setBackground(new java.awt.Color(0, 0, 0));
        BtnSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSave1.setForeground(new java.awt.Color(126, 87, 194));
        BtnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_25px.png"))); // NOI18N
        BtnSave1.setText("Save");
        BtnSave1.setBorder(null);
        BtnSave1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSave1ActionPerformed(evt);
            }
        });
        BgP1.add(BtnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, 30));

        BtnUpdate1.setBackground(new java.awt.Color(0, 0, 0));
        BtnUpdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnUpdate1.setForeground(new java.awt.Color(126, 87, 194));
        BtnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Available_Updates_25px.png"))); // NOI18N
        BtnUpdate1.setText("Update");
        BtnUpdate1.setBorder(null);
        BtnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate1ActionPerformed(evt);
            }
        });
        BgP1.add(BtnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 90, 30));

        BtnDelete1.setBackground(new java.awt.Color(0, 0, 0));
        BtnDelete1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDelete1.setForeground(new java.awt.Color(126, 87, 194));
        BtnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_25px.png"))); // NOI18N
        BtnDelete1.setText("Delete");
        BtnDelete1.setBorder(null);
        BtnDelete1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete1ActionPerformed(evt);
            }
        });
        BgP1.add(BtnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 30));

        ComboTheme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboTheme.setForeground(new java.awt.Color(204, 255, 255));
        ComboTheme.setBorder(null);
        ComboTheme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboThemeFocusGained(evt);
            }
        });
        BgP1.add(ComboTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 290, -1));

        ComboInterv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboInterv.setForeground(new java.awt.Color(204, 255, 255));
        ComboInterv.setBorder(null);
        ComboInterv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboIntervFocusGained(evt);
            }
        });
        BgP1.add(ComboInterv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 290, -1));

        javax.swing.GroupLayout fsaveLayout = new javax.swing.GroupLayout(fsave.getContentPane());
        fsave.getContentPane().setLayout(fsaveLayout);
        fsaveLayout.setHorizontalGroup(
            fsaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fsaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BgP1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fsaveLayout.setVerticalGroup(
            fsaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fsaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BgP1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BgP.setBackground(new java.awt.Color(255, 255, 255));
        BgP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BgPMouseDragged(evt);
            }
        });
        BgP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BgPMousePressed(evt);
            }
        });
        BgP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pvertical.setBackground(new java.awt.Color(54, 33, 89));
        Pvertical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnIntervenant.setBackground(new java.awt.Color(85, 65, 118));
        BtnIntervenant.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnIntervenantMouseMoved(evt);
            }
        });
        BtnIntervenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIntervenantMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Voice_Presentation_26px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Intervenants");

        javax.swing.GroupLayout BtnIntervenantLayout = new javax.swing.GroupLayout(BtnIntervenant);
        BtnIntervenant.setLayout(BtnIntervenantLayout);
        BtnIntervenantLayout.setHorizontalGroup(
            BtnIntervenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnIntervenantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        BtnIntervenantLayout.setVerticalGroup(
            BtnIntervenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnIntervenantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BtnIntervenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BtnIntervenantLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Pvertical.add(BtnIntervenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, 40));

        BtnIdentification.setBackground(new java.awt.Color(64, 43, 100));
        BtnIdentification.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnIdentificationMouseMoved(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Login_26px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Connexion");

        javax.swing.GroupLayout BtnIdentificationLayout = new javax.swing.GroupLayout(BtnIdentification);
        BtnIdentification.setLayout(BtnIdentificationLayout);
        BtnIdentificationLayout.setHorizontalGroup(
            BtnIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnIdentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        BtnIdentificationLayout.setVerticalGroup(
            BtnIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnIdentificationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BtnIdentificationLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Pvertical.add(BtnIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        BtnTheme.setBackground(new java.awt.Color(64, 43, 100));
        BtnTheme.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnThemeMouseMoved(evt);
            }
        });
        BtnTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnThemeMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_My_Topic_26px_2.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Themes");

        javax.swing.GroupLayout BtnThemeLayout = new javax.swing.GroupLayout(BtnTheme);
        BtnTheme.setLayout(BtnThemeLayout);
        BtnThemeLayout.setHorizontalGroup(
            BtnThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        BtnThemeLayout.setVerticalGroup(
            BtnThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnThemeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Proposition");
        Pvertical.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Gestion des consulations");
        Pvertical.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));
        Pvertical.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 10));

        BgP.add(Pvertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 450));

        jPanel1.setBackground(new java.awt.Color(122, 71, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Liste des propositions");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 320, 10));

        BgP.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 630, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_Math__30px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        BgP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 20));

        LblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblExit.setForeground(new java.awt.Color(204, 204, 204));
        LblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_30px.png"))); // NOI18N
        LblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblExitMouseClicked(evt);
            }
        });
        BgP.add(LblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Gestion des consultations");
        BgP.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jTable1.setBackground(new java.awt.Color(122, 71, 222));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BgP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 610, 220));

        BtnMiseAJour.setBackground(new java.awt.Color(64, 43, 100));
        BtnMiseAJour.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnMiseAJourMouseMoved(evt);
            }
        });
        BtnMiseAJour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMiseAJourMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Available_Updates_26px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Mise à jour");

        javax.swing.GroupLayout BtnMiseAJourLayout = new javax.swing.GroupLayout(BtnMiseAJour);
        BtnMiseAJour.setLayout(BtnMiseAJourLayout);
        BtnMiseAJourLayout.setHorizontalGroup(
            BtnMiseAJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMiseAJourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        BtnMiseAJourLayout.setVerticalGroup(
            BtnMiseAJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMiseAJourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BtnMiseAJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BtnMiseAJourLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BgP.add(BtnMiseAJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 130, 40));
        BgP.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        BgP.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 220, 10));

        textRecherche.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textRecherche.setForeground(new java.awt.Color(54, 33, 89));
        textRecherche.setBorder(null);
        textRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textRechercheKeyTyped(evt);
            }
        });
        BgP.add(textRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_26px.png"))); // NOI18N
        BgP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(820, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void LblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExitMouseClicked
        // TODO add your handlinhg code here:
        System.exit(0);
    }//GEN-LAST:event_LblExitMouseClicked

    private void BtnMiseAJourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMiseAJourMouseClicked
        // TODO add your handling code here:
        //jFrame1.setVisible(true);
//        new MiseAJ().setVisible(true);
        fsave.setResizable(false);
        fsave.setSize(460, 480);
        fsave.setUndecorated(true);
        fsave.setVisible(true);
        fsave.setLocationRelativeTo(null);
//        this.setVisible(false);

    }//GEN-LAST:event_BtnMiseAJourMouseClicked

    private void BgPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_BgPMouseDragged

    private void BgPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BgPMousePressed

    private void textDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDateFocusGained
        // TODO add your handling code here:

        LblDate.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_textDateFocusGained

    private void textCodePropoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCodePropoFocusGained
        // TODO add your handling code here:
        LblCodeP.setForeground(new Color(57, 117, 177));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));

    }//GEN-LAST:event_textCodePropoFocusGained

    private void textCodePropoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCodePropoMouseClicked
        // TODO add your handling code here:
        Date dt = new Date();
     textDate.setText(dt.toLocaleString());
    }//GEN-LAST:event_textCodePropoMouseClicked

    private void LblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExit1MouseClicked
        // TODO add your handling code here:
        fsave.dispose();
    }//GEN-LAST:event_LblExit1MouseClicked

    private void ResumeAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ResumeAreaFocusGained
        // TODO add your handling code here:
        LblResume.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_ResumeAreaFocusGained

    private void BtnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSave1ActionPerformed
        // TODO add your handling code here:
        if (textCodePropo.getText().equals("") || ComboInterv.getSelectedItem().equals("")
                || ComboTheme.getSelectedItem().equals("") || ResumeArea.getText().equals("")
                || textDate.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
        } else {
            pr.setIdProposition(textCodePropo.getText());
            String idI, idT;
            idI = itvn.IDinterve(ComboInterv.getSelectedItem().toString());
            pr.setIdIntervenant(idI);
            idT = thm.IDThem(ComboTheme.getSelectedItem().toString());
            pr.setIdTheme(idT);
            pr.setResumeP(ResumeArea.getText());
            pr.setDate(textDate.getText());
            pr.Ajouter();
            pr.Remplir(jTable1, "select Propositions.Id_Proposition, Intervenants.Noms,Themes.LibeleTheme,Propositions.Resume,\n"
                    + "Propositions.Date from Intervenants,Themes,Propositions\n"
                    + "where Propositions.Id_Intervenant=Intervenants.Id_Intervenant and \n"
                    + "Propositions.Id_Theme=Themes.Id_Theme");
            Nettoyer();
        }
    }//GEN-LAST:event_BtnSave1ActionPerformed

    private void ComboThemeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboThemeFocusGained
        // TODO add your handling code here:
        LblTheme.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_ComboThemeFocusGained

    private void ComboIntervFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboIntervFocusGained
        // TODO add your handling code here:
        LblInterv.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_ComboIntervFocusGained

    private void BgP1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgP1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        fsave.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_BgP1MouseDragged

    private void BgP1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgP1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BgP1MousePressed

    private void BtnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate1ActionPerformed
        // TODO add your handling code here:
        int rep = JOptionPane.showConfirmDialog(null, "Etes-vous sur de voiloir MODIFIER ??", "MODIFICATION", JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            if (textCodePropo.getText().equals("") || ComboInterv.getSelectedItem().equals("")
                    || ComboTheme.getSelectedItem().equals("") || ResumeArea.getText().equals("")
                    || textDate.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Veuillez selectioner la ligne a modifier", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
            } else {
                pr.setIdProposition(textCodePropo.getText());
                String idI, idT;
                idI = itvn.IDinterve(ComboInterv.getSelectedItem().toString());
                pr.setIdIntervenant(idI);
                idT = thm.IDThem(ComboTheme.getSelectedItem().toString());
                pr.setIdTheme(idT);
                pr.setResumeP(ResumeArea.getText());
                pr.setDate(textDate.getText());
                pr.Modifier();
                pr.Remplir(jTable1, "select Propositions.Id_Proposition, Intervenants.Noms,Themes.LibeleTheme,Propositions.Resume,\n"
                        + "Propositions.Date from Intervenants,Themes,Propositions\n"
                        + "where Propositions.Id_Intervenant=Intervenants.Id_Intervenant and \n"
                        + "Propositions.Id_Theme=Themes.Id_Theme");
                Nettoyer();
            }

        }
    }//GEN-LAST:event_BtnUpdate1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();
        textCodePropo.setText(jTable1.getValueAt(ligne, 0).toString());
        ComboInterv.setSelectedItem(jTable1.getValueAt(ligne, 1).toString());
        ComboTheme.setSelectedItem(jTable1.getValueAt(ligne, 2).toString());
        ResumeArea.setText(jTable1.getValueAt(ligne, 3).toString());
        textDate.setText(jTable1.getValueAt(ligne, 4).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete1ActionPerformed
        // TODO add your handling code here:
        int rep = JOptionPane.showConfirmDialog(null, "Etes-vous sur de voiloir SUPPRIMER ??", "MODIFICATION", JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            if (textCodePropo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Veuillez saisir le code de la proposition à supprimer", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
            } else {
                pr.setIdProposition(textCodePropo.getText());
                pr.Supprimer();
                JOptionPane.showMessageDialog(null, "La suppression à reussie", "ATTENTION!!", JOptionPane.INFORMATION_MESSAGE);
                pr.Remplir(jTable1, "select Propositions.Id_Proposition, Intervenants.Noms,Themes.LibeleTheme,Propositions.Resume,\n"
                        + "Propositions.Date from Intervenants,Themes,Propositions\n"
                        + "where Propositions.Id_Intervenant=Intervenants.Id_Intervenant and \n"
                        + "Propositions.Id_Theme=Themes.Id_Theme");
                Nettoyer();
            }

        }
    }//GEN-LAST:event_BtnDelete1ActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        Nettoyer();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void textRechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRechercheKeyTyped
        // TODO add your handling code here:
        pr.Remplir(jTable1, "select Propositions.Id_Proposition, Intervenants.Noms,Themes.LibeleTheme,Propositions.Resume,\n"
                + "Propositions.Date from Intervenants,Themes,Propositions\n"
                + "where (Propositions.Id_Intervenant=Intervenants.Id_Intervenant and \n"
                + "Propositions.Id_Theme=Themes.Id_Theme) and Themes.LibeleTheme like '%" + textRecherche.getText() + "%'");
    }//GEN-LAST:event_textRechercheKeyTyped

    private void BtnIntervenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIntervenantMouseClicked
        // TODO add your handling code here:
        new Fintervenant().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnIntervenantMouseClicked

    private void BtnThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnThemeMouseClicked
        // TODO add your handling code here:
        new Ftheme().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnThemeMouseClicked

    private void BtnIntervenantMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIntervenantMouseMoved
        // TODO add your handling code here:
        setColor(BtnIntervenant);
        resetColor(BtnIdentification);
        resetColor(BtnTheme);
        resetColor(BtnMiseAJour);
    }//GEN-LAST:event_BtnIntervenantMouseMoved

    private void BtnIdentificationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIdentificationMouseMoved
        // TODO add your handling code here:
        setColor(BtnIdentification);
        resetColor(BtnIntervenant);
        resetColor(BtnTheme);
        resetColor(BtnMiseAJour);
    }//GEN-LAST:event_BtnIdentificationMouseMoved

    private void BtnThemeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnThemeMouseMoved
        // TODO add your handling code here:
        setColor(BtnTheme);
        resetColor(BtnIdentification);
        resetColor(BtnIntervenant);
        resetColor(BtnMiseAJour);
    }//GEN-LAST:event_BtnThemeMouseMoved

    private void BtnMiseAJourMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMiseAJourMouseMoved
        // TODO add your handling code here:
        setColor(BtnMiseAJour);
    }//GEN-LAST:event_BtnMiseAJourMouseMoved
    int xx;
    int xy;

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fproposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fproposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fproposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fproposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fproposition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgP;
    private javax.swing.JPanel BgP1;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnDelete1;
    private javax.swing.JPanel BtnIdentification;
    private javax.swing.JPanel BtnIntervenant;
    private javax.swing.JPanel BtnMiseAJour;
    private javax.swing.JButton BtnSave1;
    private javax.swing.JPanel BtnTheme;
    private javax.swing.JButton BtnUpdate1;
    private javax.swing.JComboBox ComboInterv;
    private javax.swing.JComboBox ComboTheme;
    private javax.swing.JLabel LblCodeP;
    private javax.swing.JLabel LblDate;
    private javax.swing.JLabel LblExit;
    private javax.swing.JLabel LblExit1;
    private javax.swing.JLabel LblInterv;
    private javax.swing.JLabel LblResume;
    private javax.swing.JLabel LblTheme;
    private javax.swing.JPanel Pvertical;
    private javax.swing.JTextArea ResumeArea;
    private javax.swing.JFrame fsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField textCodePropo;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textRecherche;
    // End of variables declaration//GEN-END:variables
}
