/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaires;

import Entite.Intervenant;
import Entite.Proposition;
import Entite.Theme;
import java.awt.Color;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author MECHACK
 */
public class MiseAJ extends javax.swing.JFrame {

    /**
     * Creates new form MiseAJ
     */
    //        Date dt=new Date();
//        textDate.setText(dt.toLocaleString());
    Intervenant itvn = new Intervenant();
    Theme thm = new Theme();
//    Proposition prst = new Proposition();
   Fproposition fp=new Fproposition();

    public MiseAJ() {
        initComponents();
        itvn.Charger(ComboInterv);
        thm.Charger(ComboTheme);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgP = new javax.swing.JPanel();
        textDate = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        textCodePropo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        LblExit = new javax.swing.JLabel();
        LblInterv = new javax.swing.JLabel();
        LblDate = new javax.swing.JLabel();
        LblCodeP = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        LblTheme = new javax.swing.JLabel();
        LblResume = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResumeArea = new javax.swing.JTextArea();
        BtnDelete = new javax.swing.JButton();
        BtnSave1 = new javax.swing.JButton();
        BtnUpdate1 = new javax.swing.JButton();
        BtnDelete1 = new javax.swing.JButton();
        ComboTheme = new javax.swing.JComboBox();
        ComboInterv = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("c"); // NOI18N
        setUndecorated(true);

        BgP.setBackground(new java.awt.Color(32, 33, 35));
        BgP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BgPMouseDragged(evt);
            }
        });
        BgP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BgPMousePressed(evt);
            }
        });
        BgP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textDate.setBackground(new java.awt.Color(32, 33, 36));
        textDate.setForeground(new java.awt.Color(204, 255, 255));
        textDate.setBorder(null);
        textDate.setCaretColor(new java.awt.Color(255, 255, 255));
        textDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDateFocusGained(evt);
            }
        });
        BgP.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 290, 20));
        BgP.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 290, 10));

        textCodePropo.setBackground(new java.awt.Color(32, 33, 36));
        textCodePropo.setForeground(new java.awt.Color(204, 255, 255));
        textCodePropo.setBorder(null);
        textCodePropo.setCaretColor(new java.awt.Color(255, 255, 255));
        textCodePropo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCodePropoFocusGained(evt);
            }
        });
        textCodePropo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textCodePropoMouseClicked(evt);
            }
        });
        BgP.add(textCodePropo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 280, 20));
        BgP.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, 10));
        BgP.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 290, 10));

        LblExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblExit.setForeground(new java.awt.Color(57, 113, 177));
        LblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_Window_30px.png"))); // NOI18N
        LblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblExitMouseClicked(evt);
            }
        });
        BgP.add(LblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 20, 20));

        LblInterv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblInterv.setForeground(new java.awt.Color(51, 52, 54));
        LblInterv.setText("Intervenant");
        BgP.add(LblInterv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        LblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblDate.setForeground(new java.awt.Color(51, 52, 54));
        LblDate.setText("Date");
        BgP.add(LblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        LblCodeP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblCodeP.setForeground(new java.awt.Color(57, 113, 177));
        LblCodeP.setText("Code Proposition");
        BgP.add(LblCodeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        BgP.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, 10));

        LblTheme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblTheme.setForeground(new java.awt.Color(51, 52, 54));
        LblTheme.setText("Theme");
        BgP.add(LblTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        LblResume.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblResume.setForeground(new java.awt.Color(51, 52, 54));
        LblResume.setText("Resumé");
        BgP.add(LblResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        BgP.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 370, 10));

        ResumeArea.setColumns(20);
        ResumeArea.setLineWrap(true);
        ResumeArea.setRows(5);
        ResumeArea.setBorder(null);
        ResumeArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ResumeAreaFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(ResumeArea);

        BgP.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 370, 150));

        BtnDelete.setBackground(new java.awt.Color(0, 0, 0));
        BtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(126, 87, 194));
        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Broom_25px.png"))); // NOI18N
        BtnDelete.setText("Clean");
        BtnDelete.setBorder(null);
        BtnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BgP.add(BtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 90, 30));

        BtnSave1.setBackground(new java.awt.Color(0, 0, 0));
        BtnSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSave1.setForeground(new java.awt.Color(126, 87, 194));
        BtnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_25px.png"))); // NOI18N
        BtnSave1.setText("Save");
        BtnSave1.setBorder(null);
        BtnSave1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSave1ActionPerformed(evt);
            }
        });
        BgP.add(BtnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, 30));

        BtnUpdate1.setBackground(new java.awt.Color(0, 0, 0));
        BtnUpdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnUpdate1.setForeground(new java.awt.Color(126, 87, 194));
        BtnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Available_Updates_25px.png"))); // NOI18N
        BtnUpdate1.setText("Update");
        BtnUpdate1.setBorder(null);
        BtnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BgP.add(BtnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 90, 30));

        BtnDelete1.setBackground(new java.awt.Color(0, 0, 0));
        BtnDelete1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDelete1.setForeground(new java.awt.Color(126, 87, 194));
        BtnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_25px.png"))); // NOI18N
        BtnDelete1.setText("Delete");
        BtnDelete1.setBorder(null);
        BtnDelete1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BgP.add(BtnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 30));

        ComboTheme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboTheme.setForeground(new java.awt.Color(204, 255, 255));
        ComboTheme.setBorder(null);
        ComboTheme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboThemeFocusGained(evt);
            }
        });
        BgP.add(ComboTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 290, -1));

        ComboInterv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboInterv.setForeground(new java.awt.Color(204, 255, 255));
        ComboInterv.setBorder(null);
        ComboInterv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboIntervFocusGained(evt);
            }
        });
        BgP.add(ComboInterv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(460, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx;
    int xy;
    private void textDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDateFocusGained
        // TODO add your handling code here:

        LblDate.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_textDateFocusGained

    private void textCodePropoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCodePropoFocusGained
        // TODO add your handling code here:
        LblCodeP.setForeground(new Color(57, 117, 177));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
        
    }//GEN-LAST:event_textCodePropoFocusGained

    private void LblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LblExitMouseClicked

    private void ResumeAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ResumeAreaFocusGained
        // TODO add your handling code here:
        LblResume.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_ResumeAreaFocusGained

    private void ComboThemeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboThemeFocusGained
        // TODO add your handling code here:
        LblTheme.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblInterv.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_ComboThemeFocusGained

    private void ComboIntervFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboIntervFocusGained
        // TODO add your handling code here:
        LblInterv.setForeground(new Color(57, 117, 177));
        LblCodeP.setForeground(new Color(53, 52, 54));
        LblTheme.setForeground(new Color(53, 52, 54));
        LblResume.setForeground(new Color(53, 52, 54));
        LblDate.setForeground(new Color(53, 52, 54));
    }//GEN-LAST:event_ComboIntervFocusGained

    private void BgPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_BgPMouseDragged

    private void BgPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BgPMousePressed

    private void BtnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSave1ActionPerformed
        // TODO add your handling code here:
        if (textCodePropo.getText().equals("") || ComboInterv.getSelectedItem().equals("")
                || ComboTheme.getSelectedItem().equals("") || ResumeArea.getText().equals("")
                || textDate.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
        } else {
            fp.pr.setIdProposition(textCodePropo.getText());
            String idI, idT;
            idI = itvn.IDinterve(ComboInterv.getSelectedItem().toString());
            fp.pr.setIdIntervenant(idI);
            idT = thm.IDThem(ComboTheme.getSelectedItem().toString());
           fp.pr.setIdTheme(idT);
            fp.pr.setResumeP(ResumeArea.getText());
           fp.pr.setDate(textDate.getText());
            fp.pr.Ajouter();
            
            fp.pr.Remplir(fp.jTable1, "select Propositions.Id_Proposition, Intervenants.Noms,Themes.LibeleTheme,Propositions.Resume,\n"
                + "Propositions.Date from Intervenants,Themes,Propositions\n"
                + "where Propositions.Id_Intervenant=Intervenants.Id_Intervenant and \n"
                + "Propositions.Id_Theme=Themes.Id_Theme");
        }
    }//GEN-LAST:event_BtnSave1ActionPerformed

    private void textCodePropoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCodePropoMouseClicked
        // TODO add your handling code here:
         Date dt=new Date();
        textDate.setText(dt.toLocaleString());
    }//GEN-LAST:event_textCodePropoMouseClicked

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiseAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiseAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiseAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiseAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiseAJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgP;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnDelete1;
    private javax.swing.JButton BtnSave1;
    private javax.swing.JButton BtnUpdate1;
    private javax.swing.JComboBox ComboInterv;
    private javax.swing.JComboBox ComboTheme;
    private javax.swing.JLabel LblCodeP;
    private javax.swing.JLabel LblDate;
    private javax.swing.JLabel LblExit;
    private javax.swing.JLabel LblInterv;
    private javax.swing.JLabel LblResume;
    private javax.swing.JLabel LblTheme;
    private javax.swing.JTextArea ResumeArea;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField textCodePropo;
    private javax.swing.JTextField textDate;
    // End of variables declaration//GEN-END:variables
}
